---
title: "Analisis"
author: "Sebastian Robledo"
date: '2022-05-05'
output: html_document
---

```{r}
library(tidyverse)
library(margaret)
library(tidygraph)
library(rvest)
```

# Getting data 

```{r}
url <- tibble(cvlac = "https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0001430153")

cvlac_url <- "https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0001430153"

getting_cvlac <- 
  apply(url, 1, function(x){
      URL <- read_html(x['cvlac'])})
```

# Cleaning data 

```{r}
cleaning_cvlac <- # Creating a tibble
  getting_cvlac[[1]] |> 
  html_table()

for (i in 1:length(cleaning_cvlac)) {
  
  df_1 <- 
    cleaning_cvlac[[i]]
  
  df_main <- 
    df_1 |> 
    slice(-1:2)
  
}

cleaning_cvlac[[2]]

get_posgrade_clasficitation_cvlac <- function(cvlac_url) {
  
  cvlac_df = read_html(cvlac_url) |> 
    html_table()
  
  for (i in 1:length(cvlac_df)) {
    
    df_name <- 
    cvlac_df[[i]] |> 
      select(X1, X2) |> 
      filter(X1 == "Nombre") |>
      select(name = X2)
    
    df_categoria <- 
      cvlac_df[[i]] |> 
      select(X1, X2) |> 
      filter(X1 == "Categoría") |> 
      rename(Category = X1) |> 
      mutate(X2 = str_extract(X2, ".*con vigencia"),
             X2 = str_remove(X2, " con vigencia"))
      
  }
  cvlac_posgrade = cvlac_df[[1]] |> 
    filter(str_detect(string = X1, 
                      pattern = "Formación Académica")) |> 
    select(X5, X7, X9) |> 
    slice(1) |> 
    separate_rows(X5, sep = "\r\n") |> # X5
    slice(1,4) |> 
    mutate(X5 = str_trim(X5)) |> 
    nest(data = X5) |> 
    rename("X5" = data) |> 
    separate_rows(X7, sep = "\r\n") |> # X7
    slice(1,4) |> 
    mutate(X7 = str_trim(X7)) |> 
    nest(data = X7) |> 
    rename("X7" = data) |> 
    separate_rows(X9, sep = "\r\n") |> # X9
    slice(1,4) |> 
    mutate(X9 = str_trim(X9)) |> 
    nest(data = X9) |> 
    rename("X9" = data) |> 
    unnest(cols = c(X5, X7, X9)) |> 
    add_rownames() |> 
    gather(var, value, -rowname) |> 
    spread(rowname, value) |> 
    select(-var) |> 
    rename("posgrade" = 1,
           "duration" = 2) |> 
    separate(duration, sep = " - ", into = c("start", "end")) |> 
    filter(end != "de") |> # Removing not ending postgrades
    filter(posgrade %in% c("Doctorado", 
                           "Maestría/Magister",
                           "Especialización",
                           "Pregrado/Universitario")) |> 
    separate(end, into = c("Month", "year"), sep = " ") |>
    mutate(Month = if_else(Month == "de", "Enero", Month)) |> 
    mutate(Month = str_remove(Month, "de"), 
           end = str_c(Month, year, sep = " "), 
           end = parse_date(end, "%B %Y", locale = locale("es"))) |> 
    filter(end <= today()) |> 
    mutate(ranking = if_else(posgrade == "Doctorado", 3, 
                             if_else(posgrade == "Maestría/Magister", 2, 
                                     if_else(posgrade == "Especialización", 1, 
                                             0)
                                     )
                             )
           ) |> 
    slice_max(ranking) |> 
    select(posgrade) |> 
    slice(1) 
  
  if (is_empty(cvlac_posgrade$posgrade)) {
    
    cvlac_posgrade <- 
      tibble(posgrade = "Técnico")
    
  }
  
  cvlac_category <- cvlac_df[[1]] |>
    filter(X1 == "Categoría") |> 
    select(X2) 
  
  if (is_empty(cvlac_category$X2)) {
    
    cvlac_category <-  tibble(clasification = "Sin clasificar")
    
  } else {
    
    cvlac_category <- 
      cvlac_category |> 
      mutate(clasification = str_extract(string = X2, pattern = ".*\\)")) |> 
      select(clasification)
  }                  
  
  cvlac_posgrade_category <- 
    cvlac_posgrade |> 
    bind_cols(cvlac_category)
  
  
}

```


# Getting data

```{r}
profes <- 
  tibble(
    cvlac = c("https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000313220",
              "https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000942367",
              "https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000514322",
              "https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0001370943",
              "https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000212407",
              "https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000623466"),
    scholar =c("https://scholar.google.com/citations?user=IjPj8zoAAAAJ",
               "https://scholar.google.com/citations?user=bEZsTPUAAAAJ",
               "https://scholar.google.com/citations?user=PXnaNH4AAAAJ",
               "https://scholar.google.com/citations?user=MTw3GSYAAAAJ",
               "https://scholar.google.es/citations?user=1lYzwqMAAAAJ",
               "no tiene"))

profe <- 
  profes |> 
  slice(1)

# Getting the data from cvlac

data_grupos_all_profes <- 
    apply(profe, 1, function(x){
      URL <- read_html(x['cvlac'])})

data_grupos_all_profes_table <- # it has 39 elements that could be each one a dataframe 
  data_grupos_all_profes[[1]] |> 
  html_table() # Example View(data_grupos_all_profes_table[[1]])




data_getting_product <- function(data_grupos_all){
  
  grupo_df <- 
    tibble(grupo = character(),
           producto = character(),
           categoria = character())
  
  for (i in 1:length(grupos$url)) {
    
    grupo <- 
      data_grupos_all[[i]] |> 
      html_table()
    
    for (j in 1:39) {
      
      df_1 = # Creates a table with the first row 
        data_grupos_all_profes_table %>% 
        tibble() %>% 
        slice(j) %>% 
        unlist %>% 
        tibble() %>% 
        rename(producto = ".") %>% 
        mutate(grupo = grupos$grupo[i])
      
      if (length(df_1$producto) > 1) {
        
        df_2 =
          df_1 %>% 
          filter(producto != "") %>% 
          mutate(categoria = df_1$producto[1]) %>% 
          filter(str_detect(producto, "^[0-9]\\.*")) %>% 
          select(grupo, producto, categoria)
        
      } else {
        
        df_2 = 
          df_1 %>% 
          mutate(categoria = df_1$producto[1],
                 producto = "NO TIENE") %>% 
          select(grupo, producto, categoria) %>% 
          unique()
        
      }
      
      grupo_df <- 
        bind_rows(df_2,
                  grupo_df) 
      
    }
  }
  
  rm(df_1, df_2, grupo, i, j)
  return(grupo_df)
}
```

