---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

# Creando el ambiente

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(tidyverse)
library(here)
library(gt)
library(treemapify)
library(kableExtra)
library(lessR)
library(ggpubr)
```


```{r}
#source("data_getting.R")
grupo_df_articulos <-  
  read_csv(here("output", 
                "articulos.csv"))
```


# Producción General

Para este análisis filtramos el periódo de tiempo de los últimos 

```{r}
produccion_articulos <- 
  grupo_df_articulos %>% 
  filter(ano <= 2020,
         ano >= 2014) 
```



```{r}
plot_articulos_total <- 
  produccion_articulos %>% 
  count(ano) %>% 
  arrange(ano) %>% 
  ggplot(aes(x = ano, y = n, group = 1)) +
  geom_line(color = 4) +
  geom_point(color = 4) +
  xlab("año") +
  ylab("cantidad") +
  ggtitle("Producción") +
  theme_classic()
```


Producción total por tipo de producto.  

Artículos

```{r}
plot_articulos_espe<- 
  produccion_articulos %>% 
  filter(tipo_producto == "Publicado en revista especializada") %>% 
  count(ano) %>% 
  arrange(ano) %>% 
  ggplot(aes(x = ano, y = n, group = 1)) +
  geom_line(color = 4) +
  geom_point(color = 4) +
  labs(title = "Artículos en revistas especializadas",
       y = "Cantidad",
       x = "año") +
  theme_classic()
```

Artículos cortos

```{r}
plot_articulos_corto <- 
  produccion_articulos %>% 
  filter(tipo_producto == "Corto (Resumen)") %>% 
  count(ano) %>% 
  arrange(ano) %>% 
  ggplot(aes(x = ano, y = n, group = 1)) +
  geom_line(color = 4) +
  geom_point(color = 4) +
  labs(title = "Artículos Cortos (Resumen)",
       y = "Cantidad",
       x = "año") +
  theme_classic()
```

```{r}
plot_articulos_revision <- 
  produccion_articulos %>% 
  filter(tipo_producto == "Revisión (Survey)") %>% 
  count(ano) %>% 
  arrange(ano) %>% 
  ggplot(aes(x = ano, y = n, group = 1)) +
  geom_line(color = 4) +
  geom_point(color = 4) +
  labs(title = "Artículos Revisión (Survey) ",
       y = "Cantidad",
       x = "año") +
  theme_classic()
```

Gráfico general produccion artículos

```{r}
global_scientific_production_papers <- 
  ggarrange(plot_articulos_total,
            plot_articulos_espe,
        ggarrange(plot_articulos_corto, plot_articulos_revision, 
                  ncol = 2, labels = c("c", "d"), 
                  align = "h",widths = c(2,2)),  
      nrow = 3, 
      heights = c(1.5, 1, 1),
      labels = c("a","b") 
      ) 

global_scientific_production_papers
```

Análisis por países

```{r}
top_paises <- 
  produccion_articulos %>% 
  filter(pais_revista != "") %>% 
  count(pais_revista, sort = T) %>%
  slice(1:6) %>% 
  mutate(porcentaje = round(n/sum(n)*100, 
                            2))
otros_paises <- 
  produccion_articulos %>% 
  count(pais_revista, sort = T) %>%
  filter(pais_revista != "") %>% 
  mutate(porcentaje =round(n/sum(n)*100,2)) %>% 
  slice(7:n) %>% 
  summarize(n = sum(n),
            porcentaje = sum(porcentaje)) %>% 
  mutate(pais_revista = "Otros") %>% 
  select(pais_revista, n, porcentaje)

top_otras_paises <- 
  top_paises %>% 
  bind_rows(otros_paises)

top_otras_paises
```

Hay 25 productos que no presenta país. 

Análisis por revistas

```{r}
top_revistas <- 
  produccion_articulos %>% 
  count(revista, sort = T) %>%
  slice(1:6) %>% 
  mutate(porcentaje = round(n/sum(n)*100, 
                            2))

otras_revistas <- 
  produccion_articulos %>% 
  count(revista, sort = T) %>%
  mutate(porcentaje =round(n/sum(n)*100,2)) %>% 
  slice(7:n) %>% 
  summarize(n = sum(n),
            porcentaje = sum(porcentaje)) %>% 
  mutate(revista = "Otros") %>% 
  select(revista, n, porcentaje)

top_otras_revistas <- 
  top_revistas %>% 
  bind_rows(otras_revistas)

top_otras_revistas
```



# Producción por grupo 

# Producción por investigador


