grupos <- 
  tibble(grupo = c("SISCO", 
                   "JURIDICAS Y SOCIALES",
                   "GORAS",
                   "ECOSOL",
                   "NEUROCIENCIAS BASICAS Y APLICADAS",
                   "EDUCACIÓN, INFANCIA Y LENGUAS EXTRANJERAS",
                   "FAMILIA DESARROLLO Y CALIDAD DE VIDA",
                   "ESTUDIOS DE FENÓMENOS PSICOSOCIALES",
                   "CALIDAD DE VIDA",
                   "AYELEN",
                   "FARMACODEPENDENCIA Y OTRAS ADICCIONES",
                   "URBANITAS",
                   "FILOSOFÍA Y TEOLOGIA CRITICA",
                   "CONTAS",
                   "LUES"),
         url = c("https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000008639", 
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000001658", 
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000002701", 
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000008267", 
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000011901", 
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000002700", 
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000010166", 
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000002630", 
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000003000", 
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000011499", 
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000008266", 
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000002699", 
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000004872", 
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000002534", 
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000002642")) 
