grupos <- 
  tibble(grupo = c("SISCO", 
                   "JURIDICAS Y SOCIALES",
                   "GORAS",
                   "ECOSOL",
                   "NEUROCIENCIAS BASICAS Y APLICADAS",
                   "EDUCACIÓN, INFANCIA Y LENGUAS EXTRANJERAS",
                   "FAMILIA DESARROLLO Y CALIDAD DE VIDA",
                   "ESTUDIOS DE FENÓMENOS PSICOSOCIALES",
                   "CALIDAD DE VIDA",
                   "AYELEN",
                   "FARMACODEPENDENCIA Y OTRAS ADICCIONES",
                   "URBANITAS",
                   "FILOSOFÍA Y TEOLOGIA CRITICA",
                   "CONTAS",
                   "LUES"),
         url = c("https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000008639", # SISCO
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000002703", # JURIDICAS Y SOCIALES
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000002701", # GORAS
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000008267", # ECOSOL
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000011901", # NEUROCIENCIAS BASICAS Y APLICADAS
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000002700", # EDUCACIÓN, INFANCIA Y LENGUAS EXTRANJERAS
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000002698", # FAMILIA DESARROLLO Y CALIDAD DE VIDA
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000002630", # ESTUDIOS DE FENÓMENOS PSICOSOCIALES
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000003174", # CALIDAD DE VIDA
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000011499", # AYELEN
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000008266", # FARMACODEPENDENCIA Y OTRAS ADICCIONES
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000002699", # URBANITAS
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000004872", # FILOSOFÍA Y TEOLOGIA CRITICA
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000002534", # CONTAS
                 "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000002642")) # LUES


scholar_id <- 
  tibble(researcher =c("Angela María  Velásquez  Velásquez",
                       "Alfredo Manuel Ghiso Cotos",
                       "Jenny Marcela Acevedo Valencia",
                       "Natalia Andrea Alzate Alzate",
                       "Ruby Stella Cabrera Jaramillo",
                       "Mauricio alejandro bedoya jimenez",
                       "MARLON DAVID GARCIA JIMENEZ",
                       "Farley Sary Rojas  Restrepo",
                       "Carlos Eduardo Castaño Rios",
                       "Candy Lorena Chamorro  Gonzalez",
                       "Carolina Vila Porras",
                       "Andrés Felipe Agudelo Zorrilla",
                       "andres escobar vasquez",
                       "Paloma  Marín Escobar",
                       "Manuel David Gómez Erazo",
                       "Kelly Vargas García",
                       "Juan Sebastián Hernández Valencia",
                       "Juan Esteban Londoño Betancur",
                       "Andrés Alfredo Castrillón Castrillón",
                       "Marcos VEGA SEÑA",
                       "Juan Diego López Medina",
                       "Jhoeen Sneyder Rojas Díaz",
                       "Edwin Andrés Sepúlveda Cardona",
                       "Carlos Suárez Quiceno",
                       "CARLOS ANDRÉS TREJOS GIL",
                       "Lina María Rendón López",
                       "Alexander Rodríguez Bustamante",
                       "YUSTY CAROLINA RESTREPO SEGURA",
                       "Olena Klimenko Klimenko",
                       "Mauricio alejandro bedoya jimenez",
                       "Maricelly Gómez Vargas",
                       "Maria Victoria Restrepo Tobón",
                       "Lucas Davila Cañas",
                       "Lina María Gallego Ramírez",
                       "Jorge Hernán González Cortés",
                       "Gloria Maria Lopez Arboleda",
                       "Gloria Cecilia Cardona Rios",
                       "Gladys Janeth Ríos Palacio",
                       "Eliza Kratc  Gil",
                       "David Ignacio Molina Velásquez",
                       "SANDRA MILENA RESTREPO ESCOBAR",
                       "Dubis Marcela Rincon Barreto",
                       "Viviana Carmenza  Avila Navarrete",
                       "Benilda Layne Bernal",
                       "Estelio Jose Angulo",
                       "Carlos RODRIGUEZ SANTOS",
                       "Argemiro Jose AMAYA BUELVAS",
                       "Victor Teran Reales",
                       "HUBER YECID CASTRO ESCOBAR",
                       "Sandra Isabel Mejia Zapata",
                       "Paula Vanessa Sanchez Agudelo",
                       "María Cristina Correa Duque",
                       "Magda Victoria Díaz Alzate",
                       "Katy Luz Millán Otero",
                       "Jose Alcides Castro Acevedo",
                       "John Harvy Arcia Grajales",
                       "Herwin Eduardo Cardona Quitián",
                       "Heidi Smith Pulido Varon",
                       "Carolina  Valdés Henao",
                       "ANYERSON STITHS GOMEZ  TABARES",
                       "Nicolasa María Durán Palacio",
                       "Yubisay Noiraly Mejías Peña",
                       "OVIDIO HERRERA RIVERA",
                       "Mónica María Castañeda Gómez",
                       "Lucas Davila Cañas",
                       "Ledy Maryory  Bedoya  Cardona",
                       "Carolina  Vásquez  López",
                       "Alexander Rodríguez Bustamante",
                       "Edison Francisco Viveros Chavarría",
                       "LEISY MAGDALI  ARROYAVE TABORDA",
                       "YUSTY CAROLINA RESTREPO SEGURA",
                       "Sonia Ruth Quintero  Arrubla",
                       "Oscar Peláez Henao",
                       "Jose Wilmar Pino Montoya",
                       "José Vicente Abad Olaya",
                       "José Federico Agudelo Torres",
                       "Claudia Marcela Arana Medina",
                       "Bairon Jaramillo Valencia",
                       "Adriana Maria Gallego Henao",
                       "Mónica María Alvarez Gallego",
                       "Yamile Cardona Maya",
                       "Víctor Daniel  Gil Vera",
                       "andres mauricio grisales aguirre",
                       "Edgar Andrés Chavarriaga Miranda",
                       "Franklin Ferraro Gómez",
                       "GABRIEL JAIME  POSADA HERNANDEZ",
                       "Ingrid Durley Torres  Pardo",
                       "Lina Maria Montoya  Suárez",
                       "Luis Fernando Cardona Palacio",
                       "Maria Julia Nieto Callejas",
                       "MARIO ALEJANDRO LÓPEZ OCAMPO",
                       "Mauricio López Bonilla",
                       "Sara María Aguilar Sierra",
                       "Shirlene Patricia  Vega ROYERO",
                       "SUYIS YAJAIRA LOZANO GARCÍA",
                       "Walter Hugo Arboleda Mazo",
                       "Elvigia Cardona  ZULETA",
                       "Jorge Eduardo Vasquez Santamaria",
                       "Dany Steven Gómez Agudelo",
                       "David Andrés Díez Gómez",
                       "JORGE IVAN GAVIRIA MESA",
                       "Juan Esteban  Aguirre  Espinosa",
                       "Laura Victoria  Cardenas Rojas",
                       "Maria Isabel  Uribe López",
                       "Mauricio Mejia Lobo",
                       "Mayda Soraya Marín  Galeano",
                       "Roberto Mauricio Romero Cárdenas",
                       "Jenniffer Londoño Jurado",
                       "Jormaris Martínez Gómez",
                       "Luis Fernando Quintero Arango",
                       "ana maría  chaux gutiérrez",
                       "Daniel Muñoz Quintero",
                       "Jaime Alberto Beltrán Ríos",
                       "JORGE IVAN JIMENEZ  SANCHEZ",
                       "José Antonio López Giraldo",
                       "Mauricio alejandro bedoya jimenez",
                       "Néstor Eduardo Flórez  OVIEDO",
                       "Sandra Milena Malavera Pineda",
                       "Sebastián Arias Giraldo",
                       "Sindy Yuliana Gallego Tavera",
                       "Sugey Elena Anaya García",
                       "Ubeimar Aurelio Osorio Atehortúa",
                       "Víctor Daniel  Gil Vera",
                       "Victor Hugo Meriño Córdoba",
                       "YAMARU DEL VALLE CHIRINOS ARAQUE",
                       "Fredy De Jesus Fernández Márquez",
                       "Juan Santiago Calle Piedrahita",
                       "Olga Lucía Arboleda Álvarez",
                       "Martha del Socorro  Alzate Cárdenas",
                       "Doralice Ortiz Ortiz",
                       "Jaime Antero Arango Marin",
                       "Laura Elena Zapata Jiménez",
                       "Maria Isabel GUERRERO MOLINA",
                       "Oswaldo Antonio Salgado Cañaveral",
                       "Pedro Luis Duque Hurtado",
                       "SEBASTIAN ROBLEDO GIRALDO",
                       "Victoria Blaquised Rivera",
                       "YAMARU DEL VALLE CHIRINOS ARAQUE",
                       "Olber Eduardo Arango Tobón",
                       "Julio Antonio  Olivera La Rosa",
                       "ANYERSON STITHS GOMEZ  TABARES",
                       "Catalina Quintero López",
                       "César Andrés  Carmona Cardona",
                       "Claudia Marcela Arana Medina",
                       "Daniel alfredo landinez martinez",
                       "Isabel Cristina Puerta Lopera",
                       "Juan Diego Betancur Arias",
                       "Omar Augusto Amador Sánchez",
                       "Paula Andrea Montoya Zuluaga",
                       "Víctor Daniel  Gil Vera",
                       "Carmen Ysabel Martínez de Meriño"
  ),
  id_scholar = c("BbHGEOcAAAAJ&hl",
                 "Cj2hqc4AAAAJ&hl",
                 "ul0fN9wAAAAJ",
                 "sAljacYAAAAJ",
                 "_Swwv5oAAAAJ",
                 "wDY8t8gAAAAJ",
                 "zwGXNrAAAAAJ",
                 "Q0JvK8cAAAAJ&hl",
                 "LRUmr_cAAAAJ",
                 "vOpE5gUAAAAJ&hl",
                 "Kd1AWwkAAAAJ",
                 "GJRrDiEAAAAJ&hl",
                 "HgkxSmsAAAAJ",
                 "sRuFPZsAAAAJ",
                 "ZN11BuUAAAAJ",
                 "FSZpothCoVgC",
                 "YulZHwUAAAAJ",
                 "kmGAVz0AAAAJ&hl",
                 "09VhuCYAAAAJ",
                 "h3lf-PsAAAAJ",
                 "5rZW9KcAAAAJ",
                 "SuGmv1UAAAAJ",
                 "KH7yFUsAAAAJ",
                 "1ATgz8UAAAAJ",
                 "Hw7ZjsEAAAAJ",
                 "6uKvLyYAAAAJ",
                 "F2CwSh0AAAAJ",
                 "BhyHthYAAAAJ",
                 "0r6pOxoAAAAJ",
                 "wDY8t8gAAAAJ",
                 "XNkEWKgAAAAJ",
                 "R5D6vOoAAAAJ",
                 "mCT8CTsAAAAJ",
                 "WPEpjKwAAAAJ",
                 "BfjlQ8QAAAAJ",
                 "iR3xAfEAAAAJ",
                 "zt9fGF0AAAAJ",
                 "I8eYYScAAAAJ",
                 "r1I0YJYAAAAJ",
                 "xCRCMooAAAAJ",
                 "eHauI0IAAAAJ",
                 "pjSE_C0AAAAJ",
                 "c1XCBZ0AAAAJ",
                 "Cw9U7VIAAAAJ",
                 "NRo7HZIAAAAJ",
                 "FmH8nIkAAAAJ&hl",
                 "kyNzB50AAAAJ",
                 "lOUtSkIAAAAJ&hl",
                 "jsQSXroAAAAJ",
                 "IiNO1TwAAAAJ",
                 "SosfQ4QAAAAJ",
                 "GsRFkT8AAAAJ",
                 "C9ZdWuEAAAAJ",
                 "-RwHy5gAAAAJ",
                 "iXbqjRQAAAAJ",
                 "dyMWHucAAAAJ",
                 "Ojpa1lAAAAAJ",
                 "5ZIDAcEAAAAJ",
                 "r-CYB90AAAAJ",
                 "504O9wUAAAAJ",
                 "ULpZsLAAAAAJ",
                 "82UcqOgAAAAJ",
                 "gcjNnGEAAAAJ",
                 "-4_OX-cAAAAJ&hl",
                 "R5D6vOoAAAAJ",
                 "6vKCOHYAAAAJ",
                 "2rKBGpEAAAAJ",
                 "KcmOLKYAAAAJ",
                 "F2CwSh0AAAAJ",
                 "00wsl70AAAAJ",
                 "KVBCFWkAAAAJ",
                 "BhyHthYAAAAJ",
                 "Bo9j0C0AAAAJ",
                 "WasxVdYAAAAJ&hl",
                 "LhNZ3BgAAAAJ",
                 "trVcxggAAAAJ",
                 "RHbX7ioAAAAJ",
                 "bEplYn8AAAAJ",
                 "2b28iRkAAAAJ",
                 "zts5sHIAAAAJ",
                 "sw3ZQ-kAAAAJ",
                 "Y2p7DZwAAAAJ&hl",
                 "1-4BHH8AAAAJ&hl",
                 "-urmP7EAAAAJ&hl",
                 "qSOzbFwAAAAJ",
                 "DNeZOJUAAAAJ&hl",
                 "_uwscnEAAAAJ&hl",
                 "nchHazIAAAAJ&hl",
                 "7Y-8siIAAAAJ&hl",
                 "hOgH7HAAAAAJ&hl",
                 "XuxhAV0AAAAJ&hl",
                 "fDz4KKEAAAAJ&hl",
                 "lQqAfmwAAAAJ&hl",
                 "_RFI4pkAAAAJ&hl",
                 "yQ7g9xUAAAAJ&hl",
                 "z1vjdF0AAAAJ",
                 "uFJHflEAAAAJ&hl",
                 "SteXGqYAAAAJ&hl",
                 "v8GT-VAAAAAJ&hl",
                 "YaysRIIAAAAJ&hl",
                 "sOWnFLUAAAAJ&hl",
                 "mh-AeYwAAAAJ",
                 "9QD3rjkAAAAJ",
                 "VlC916UAAAAJ",
                 "QbjM9m0AAAAJ",
                 "RCtbsjMAAAAJ",
                 "1x5m4ywAAAAJ",
                 "YdeOxzsAAAAJ",
                 "XFBxR6kAAAAJ",
                 "3vFUn4wAAAAJ",
                 "vu06sqwAAAAJ",
                 "ZBh57LoAAAAJ&hl",
                 "Fp-EtWwAAAAJ",
                 "bjYfxdwAAAAJ",
                 "FF97f1MAAAAJ",
                 "jCYg-jsAAAAJ",
                 "wDY8t8gAAAAJ",
                 "3oUj4vUAAAAJ",
                 "qvBehKYAAAAJ",
                 "V3rISaoAAAAJ",
                 "YNwDcOcAAAAJ",
                 "qPSF-CgAAAAJ",
                 "MTw3GSYAAAAJ&hl",
                 "1-4BHH8AAAAJ",
                 "dsuvvNEAAAAJ",
                 "NzpSyf0AAAAJ",
                 "1aXOG-MAAAAJ",
                 "sXijM8EAAAAJ",
                 "94o7mbgAAAAJ",
                 "bEZsTPUAAAAJ",
                 "syisuJcAAAAJ",
                 "qn1Kr9EAAAAJ",
                 "IjPj8zoAAAAJ",
                 "PXnaNH4AAAAJ",
                 "R1p685wAAAAJ",
                 "tEPrd4IAAAAJ&hl",
                 "RGUTAfEAAAAJ&hl",
                 "oZ4fX-IAAAAJ&hl",
                 "NzpSyf0AAAAJ",
                 "nIWo18gAAAAJ",
                 "p1jzZwMAAAAJ&hl",
                 "504O9wUAAAAJ",
                 "jp1wLg4AAAAJ",
                 "LN9Fg-8AAAAJ",
                 "bEplYn8AAAAJ",
                 "HWzOMPwAAAAJ",
                 "I7x7Oo8AAAAJ",
                 "Rb881xwAAAAJ",
                 "2EdSYP0AAAAJ&hl",
                 "_SE2G3UAAAAJ",
                 "1-4BHH8AAAAJ"
  ))

