---
title: "Margaret"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(here)
library(DT)
library(plotly)
library(readxl)
library(shiny)
library(crosstalk)
```

```{r global}
articulos_unicos_2016_2020 <- 
  read_csv(here("output",
                "articulos.csv")) |> 
  filter(ano >= 2016,
         ano <=2020)

grupos_general <- 
  read_csv(here("output",
                "grupos_general.csv"))

investigadores_general <- 
  read_csv(here("output", 
                "investigadores.csv"))

grupos_inves <-
  read_csv(here("data",
                "grupos.csv"))

grupos_indi <- read_csv(here("data",
                             "df_researcher.csv"))

filename <-here("output","grupos_produccion.xlsx")

sheets <- openxlsx::getSheetNames(filename)
produccion_grupos <- lapply(sheets,openxlsx::read.xlsx,xlsxFile=filename)
names(produccion_grupos) <- sheets


grupos_produccion_articulos <- read_xlsx(here("output","grupos_produccion.xlsx"), 
    sheet = "articulos")
```


# General

## Column {.tabset}

### Grupos

```{r}
grupos_general |> 
  select(grupo, clasificacion, sum_papers, departamento , url,
         fecha_creacion,lider, email, area_conocimiento_1) |> 
  mutate(url= str_c("<a href=",
                     url,
                     ">Link</a>")) |> 
  datatable(options = list(pageLength = 15),
            escape = FALSE,
            colnames = c("Grupo", "Clasificaci?n", "Cantidad Articulo",
                         "Departamento","GrupLAC", 
                         "Fecha Creaci?n", "Lider", "Email", 
                         "?rea de Conocimiento"))
```

### Investigadores

```{r}
investigadores_general |> 
  mutate(url = str_c("<a href=","\"",
                     url,
                     "\"",
                     ">Link</a>"),
         scholar = str_c("<a href=","\"",
                         "https://scholar.google.com/citations?user=",
                         id_scholar,
                         "\"",
                         ">Scholar</a>")) |>
  select(-vinculacion,
         -fin_vinculacion) |> 
  rename(Investigador = integrantes,
         Produccion = total_papers,
         Horas = horas_dedicacion,
         CvLAC = url,
         Grupo = grupo,
         Inicio = inicio_vinculacion,
         Formacion = posgrade,
         ) |> 
  select(Investigador,
         Produccion,
         h_index,
         Formacion,
         Grupo,
         Inicio,
         CvLAC,
         scholar) |> 
  datatable(options = list(pageLength = 15),
            escape = FALSE,
            colnames = c("Investigador", "Categoria", "Producción", "H index", "Formación",
                         "Grupo", "Inicio", "CvLAC", "Scholar"))
```

### Productos

```{r}
articulos_unicos_2016_2020 |>
  select(-id) |> 
  mutate(DOI = str_extract(DOI, "\\d.*")) |> 
  mutate(DOI =  str_c("<a href=","\"",
                         "https://doi.org/",
                         DOI,
                         "\"",
                         ">Link</a>")) |>  
  datatable(options = list(pageLength = 15),
            escape = FALSE,
            colnames = c("Grupo", "Categoría", "Tipo producto",
                         "Título", "País revista", "Revista", 
                         "ISSN", "Año", "Volumen", "Fasc",
                         "Paginas", "DOI", "Autores"))
```

### Paises
```{r}
paises <- articulos_unicos_2016_2020 |> 
  count(pais_revista, sort = TRUE)
paises$porcentaje <- round(prop.table(paises$n),3)*100 
paises |> 
  mutate(porcentaje = str_c(porcentaje," %")) |> 
  datatable(options = list(pageLength = 20), 
            colnames = c('País revista', 'Cantidad', 'Porcentajes')) 
```
### Revistas
```{r}
revistas <- articulos_unicos_2016_2020 |> 
  count(revista, sort = TRUE)
revistas$porcentaje <- round(prop.table(revistas$n),3)*100 
revistas |>
  mutate(porcentaje = str_c(porcentaje," %")) |> 
  datatable(options = list(pageLength = 20), 
            colnames = c('Revista', 'Cantidad', 'Porcentajes'))
```

# Grupos general en cifras

Column {data-width=500}
--------------------------------------

### Grupos de investigación
```{r}
data1 <- grupos_inves |> count(clasificacion) |> arrange(desc(clasificacion))
fig1 <- plot_ly(data1, x = ~clasificacion, y = ~n, type = 'bar')
fig1 <- fig1 %>% layout(title = 'Clasificación',
         xaxis = list(title = ""),
         yaxis = list(title = ""))
fig1
```

Column {data-width=500}
-----------------------------------

### Evolución temporal
```{r}
data3 <- grupos_produccion_articulos |> 
  select(categoria, ano, grupo) |> 
  filter(ano >= 2016, ano <=2020) |> 
  count(ano, sort = FALSE, name = "producciones")
fig3 <- plot_ly(data3, x = ~ano, y = ~producciones, type = 'scatter', mode = 'lines')
fig3 <- fig3 %>% layout(title = "Producción articulos",
         xaxis = list(title = ""),
         yaxis = list(title = ""))

fig3
```

# Grupos individual en cifras

Column {data-width=200} 
-----------------------------------

```{r}
data4 <- grupos_indi |> select(grupo , categoria) |> 
  group_by(grupo, categoria) |> 
  summarise(n = n()) 

data5 <- grupos_indi |> select(grupo , ultima_formacion_academica) |> 
  group_by(grupo, ultima_formacion_academica) |> 
  summarise(n = n()) |> 
  rename(m = n,
         formacion = ultima_formacion_academica)

matriz <- matrix(NA, nrow = 5, ncol = 3)
  
matriz <- data.frame(matriz) |> 
  rename(grupo = X1,
         formacion = X2,
         m = X3)

data5 <- rbind(data5, matriz) |> 
  rename(categoria = 2)

data6 <- merge(data5, data4, by = c("grupo", "categoria"), all = TRUE)

datos_compartidos <- crosstalk::SharedData$new(data6)

filter_select("categoria", "Grupo", datos_compartidos, ~grupo)

```

Column {data-width=400}
-----------------------------------
### Categorias investigadores por grupo
```{r}
p0 <- datos_compartidos |> 
  plot_ly(labels= ~categoria, values=~n, type = 'pie')
p0 <- p0 %>% layout(title = 'Categorias',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
p0
```

Column {data-width=400}
-----------------------------------
### Formacion por grupo
```{r}
p0 <- datos_compartidos |> 
  plot_ly(labels= ~categoria, values=~m, type = 'pie')
p0 <- p0 %>% layout(title = 'Formacion',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
p0

```

# Produccion anual por grupos en cifras

Column {data-width=200} 
-----------------------------------

```{r}
data7 <- articulos_unicos_2016_2020 |> 
  select(categoria, ano, grupo) |> 
  count(ano, grupo, sort = FALSE, name = "producciones")

datos_anual <- crosstalk::SharedData$new(data7)

filter_select("Produccion", "Grupo", datos_anual, ~grupo)

```

Column {data-width=800}
-----------------------------------
### produccion anual
```{r}
p1 <- datos_anual |> 
  plot_ly(x = ~ano, y = ~producciones, type = 'scatter', mode = 'lines')
p1 <- p1 %>% layout(title = "Produccion articulos",
         xaxis = list(title = ""),
         yaxis = list(title = ""))

p1
```
