---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(readxl)
library(tidyverse)
library(rvest)
library(here)
library(dplyr)
library(plotly)
library(ggplot2)
library(DT)

filename <-"grupos_produccion.xlsx"

sheets <- openxlsx::getSheetNames(filename)
produccion_grupos <- lapply(sheets,openxlsx::read.xlsx,xlsxFile=filename)
names(produccion_grupos) <- sheets
categorias <- read_excel(here("scripts","categorias.xlsx")) 
```

Categorias
===========================

Column {data-width=650}
-----------------------------------------------------------------------
### Categorias con producción 

```{r}
table <- categorias %>% DT::datatable()
table

```

### Categorias con mayor producción

```{r}
fig <- plot_ly(
  x = head(categorias$categoria, 10),
  y = head(categorias$cantidad, 10),
  name = names(categorias$categoria),
  type = "bar"
)
fig
```


## {.tabset}
### Artículos
```{r}
articulos <- produccion_grupos[["articulos"]] %>% select(ano) %>% count(ano, sort = FALSE,
                                                         name = "Producciones") %>% 
  filter(ano >= 2016)

fig2 <- plot_ly(articulos, x = ~ano)
fig2 <- fig2 %>%  add_trace(y=~Producciones, 
                            type = 'scatter', mode = 'lines',
                            line = list(color='rgba(255,116,0, 1)', width = 4))
fig2 <- fig2 %>% layout(title="Producción en la categoría Artículo desde el 2016")

fig2

```



### Trabajos dirigidos


```{r}

```
