---
title: "Margaret"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(here)
library(DT)
library(plotly)
library(readxl)
library(shiny)
```

```{r global}
articulos_unicos_2016_2020 <- 
  read_csv(here("data",
                "articulos_unicos.csv")) |> 
  filter(ano >= 2016,
         ano <=2020)

grupos_general <- 
  read_csv(here("output",
                "general_grupos.csv"))

investigadores_general <- 
  read_csv(here("output", 
                "df_researcher.csv"))

filename <-here("output","grupos_produccion.xlsx")

sheets <- openxlsx::getSheetNames(filename)
produccion_grupos <- lapply(sheets,openxlsx::read.xlsx,xlsxFile=filename)
names(produccion_grupos) <- sheets
```


# General
```{r}

```

## Column {.tabset}

### Grupos

```{r}
grupos_general |> 
  datatable(options = list(pageLength = 15),
            escape = FALSE)
```

### Investigadores

```{r}
investigadores_general |> 
  mutate(url = str_c("<a href=","\"",
                     url,
                     "\"",
                     ">Link</a>"),
         scholar = str_c("<a href=","\"",
                         "https://scholar.google.com/citations?user=",
                         id_scholar,
                         "\"",
                         ">Scholar</a>")) |>
  select(-vinculacion,
         -fin_vinculacion) |> 
  rename(Investigador = integrantes,
         Categoria = categoria,
         Produccion = cantidad,
         Horas = horas_dedicacion,
         CvLAC = url,
         Grupo = grupo,
         Inicio = inicio_vinculacion,
         Formacion = ultima_formacion_academica,
         ) |> 
  select(Investigador,
         Categoria,
         Produccion,
         h_index,
         Formacion,
         Grupo,
         Inicio,
         CvLAC,
         scholar) |> 
  datatable(options = list(pageLength = 10),
            escape = FALSE)
```

### Paises
```{r}
articulos_unicos_2016_2020 |> 
  count(pais_revista, sort = TRUE) |> 
  datatable(options = list(pageLength = 10))
```
### Revistas
```{r}
articulos_unicos_2016_2020 |> 
  count(revista, sort = TRUE) |> 
  datatable(options = list(pageLength = 10))
```
# Grupos - General

# Grupos - Individual

## column {.sidebar}
```{r}
selectInput("n_breaks",
            label = "Grupos de investigación: ",
            choices = c("SISCO", "ECOSOL", "GORAS","JURIDICAS Y SOCIALES",
                        "NEUROCIENCIAS BASICAS Y APLICADAS",
                        "EDUCACIÓN, INFANCIA Y LENGUAS EXTRANJERAS",
                        "FAMILIA DESARROLLO Y CALIDAD DE VIDA",
                        "ESTUDIOS DE FENÓMENOS PSICOSOCIALES",
                        "CALIDAD DE VIDA","AYELEN",
                        "FARMACODEPENDENCIA Y OTRAS ADICCIONES",
                        "URBANITAS",
                        "FILOSOFÍA Y TEOLOGIA CRITICA","CONTAS",
                        "LUES"), selected = 20)

checkboxGroupInput("chklvl", label = "Categorias",
                   choices = c("A1","A","B","C"))
submitButton("Aplicar")
```

Grupos - Top
======================================
Column {data-width=330}
-------------------------------
### SISCO
```{r}
grupos_1 <- produccion_grupos[[3]] |> 
  filter(ano >=2016, ano <=2020) |> 
  select(grupo, ano) |> 
  filter(grupo == "SISCO") |> 
  mutate(Año = str_trim(ano)) %>% 
  select(-ano) |> 
  count(Año, sort = FALSE, name="cantidad")

figura_1 <- plot_ly(grupos_1, x=~Año)
figura_1 <- figura_1 %>%  add_trace(y=~cantidad, 
                            type = 'scatter', mode = 'lines',
                            line = list(color='rgba(255,116,0, 1)', width = 4))

figura_1
```

### NEUROCIENCIAS BASICAS Y APLICADAS
```{r}
grupos_4 <- produccion_grupos[[3]] |> 
  filter(ano >=2016, ano <=2020) |> 
  select(grupo, ano) |> 
  filter(grupo == "NEUROCIENCIAS BASICAS Y APLICADAS") |> 
  mutate(Año = str_trim(ano)) %>% 
  select(-ano) |> 
  count(Año, sort = FALSE, name="cantidad")

figura_4 <- plot_ly(grupos_4, x=~Año)
figura_4 <- figura_4 %>%  add_trace(y=~cantidad, 
                            type = 'scatter', mode = 'lines',
                            line = list(color='rgba(255,116,0, 1)', width = 4))

figura_4
```


Column {data-width=330}
-------------------------------
### ESTUDIOS DE FENOMENOS PSICOSOCIALES
```{r}
grupos_2 <- produccion_grupos[[3]] |> 
  filter(ano >=2016, ano <=2020) |> 
  select(grupo, ano) |> 
  filter(grupo == "ESTUDIOS DE FENÃ“MENOS PSICOSOCIALES") |> 
  mutate(Año = str_trim(ano)) %>% 
  select(-ano) |> 
  count(Año, sort = FALSE, name="cantidad")

figura_2 <- plot_ly(grupos_2, x=~Año)
figura_2 <- figura_2 %>%  add_trace(y=~cantidad, 
                            type = 'scatter', mode = 'lines',
                            line = list(color='rgba(255,116,0, 1)', width = 4))
figura_2
```
### GORAS
```{r}
grupos_5 <- produccion_grupos[[3]] |> 
  filter(ano >=2016, ano <=2020) |> 
  select(grupo, ano) |> 
  filter(grupo == "GORAS") |> 
  mutate(Año = str_trim(ano)) %>% 
  select(-ano) |> 
  count(Año, sort = FALSE, name="cantidad")

figura_5 <- plot_ly(grupos_5, x=~Año)
figura_5 <- figura_5 %>%  add_trace(y=~cantidad, 
                            type = 'scatter', mode = 'lines',
                            line = list(color='rgba(255,116,0, 1)', width = 4))

figura_5
```


Column {data-width=330}
-------------------------------
### EDUCACION, INFANCIA Y LENGUAS EXTRANJERAS
```{r}
grupos_3 <- produccion_grupos[[3]] |> 
  filter(ano >=2016, ano <=2020) |> 
  select(grupo, ano) |> 
  filter(grupo == "EDUCACIÃ“N, INFANCIA Y LENGUAS EXTRANJERAS") |> 
  mutate(Año = str_trim(ano)) |>  
  select(-ano) |> 
  count(Año, sort = FALSE, name="cantidad")

figura_3 <- plot_ly(grupos_3, x=~Año)
figura_3 <- figura_3 |> add_trace(y=~cantidad, 
                            type = 'scatter', mode = 'lines',
                            line = list(color='rgba(255,116,0, 1)', width = 4))

figura_3
```

### FARMACODEPENDENCIA Y OTRAS ADICCIONES
```{r}
grupos_6 <- produccion_grupos[[3]] |> 
  filter(ano >=2016, ano <=2020) |> 
  select(grupo, ano) |> 
  filter(grupo == "FARMACODEPENDENCIA Y OTRAS ADICCIONES") |> 
  mutate(Año = str_trim(ano)) |>  
  select(-ano) |> 
  count(Año, sort = FALSE, name="cantidad")

figura_6 <- plot_ly(grupos_6, x=~Año)
figura_6 <- figura_6 |> add_trace(y=~cantidad, 
                            type = 'scatter', mode = 'lines',
                            line = list(color='rgba(255,116,0, 1)', width = 4))

figura_6
```


# Grupos - Detalle

# Investigadores - General

# Investigadores - Individual

## column{.sidebar}
```{r}
selectInput("n_breaks",
            label = "Investigadores: ",
            choices = c("Yamile", "Yoder", "Franklin"), selected = 20)

checkboxGroupInput("chktipinv", label = "Tipo de investigador: ",
                   choices = c("Senior","Junior","Asociado","Emérito"))
submitButton("Aplicar")
```

Investigadores - Top
=================================
```{r}
investigadores<- produccion_grupos[[3]] |> 
  filter(ano >=2016, ano <=2020) |> 
  separate_rows(autores,sep = ", ") |> 
  select(autores, grupo) |> 
  left_join(investigadores_general, by=c("autores"="integrantes")) |> 
  filter(grupo.x == grupo.y) |> 
  count(autores, sort = TRUE, name = "Producciones")
```

Column {data-width=400}
-------------------------------
### Investigadores Top
```{r}
tabla <- investigadores |> 
  datatable(options = list(pageLength = 10))
tabla
```


Column {data-width=300}
-------------------------------

### BAIRON JARAMILLO VALENCIA
```{r}
d_1 <- produccion_grupos[[3]] |> 
  separate_rows(autores, sep = ", ") |> 
  filter(autores == "BAIRON JARAMILLO VALENCIA", 
         ano <=2020, ano >=2016) |>
  select(ano) |> 
  mutate(Año = str_trim(ano)) |> 
  select(-ano) |> 
  count(Año, sort=FALSE, name="Producciones")

g_1 <- plot_ly(d_1, x=~Año)
g_1 <- g_1 |> add_trace(y=~Producciones, 
                            type = 'scatter', mode = 'lines',
                            line = list(color='rgba(104,255,0, 1)', width = 6))

g_1
```

### EDISON FRANCISCO VIVEROS CHAVARRIA
```{r}
d_3 <- produccion_grupos[[3]] |> 
  separate_rows(autores, sep = ", ") |> 
  filter(autores == "EDISON FRANCISCO VIVEROS CHAVARRIA", 
         ano <=2020, ano >=2016) |>
  select(ano) |> 
  mutate(Año = str_trim(ano)) |> 
  select(-ano) |> 
  count(Año, sort=FALSE, name="Producciones")

g_3 <- plot_ly(d_3, x=~Año)
g_3 <- g_3 |> add_trace(y=~Producciones, 
                            type = 'scatter', mode = 'lines',
                            line = list(color='rgba(104,255,0, 1)', width = 6))

g_3
```


Column {data-width=300}
-------------------------------

### FRANKLIN FERRARO GOMEZ
```{r}
d_2 <- produccion_grupos[[3]] |> 
  separate_rows(autores, sep = ", ") |> 
  filter(autores == "FRANKLIN FERRARO GOMEZ", 
         ano <=2020, ano >=2016) |>
  select(ano) |> 
  mutate(Año = str_trim(ano)) |> 
  select(-ano) |> 
  count(Año, sort=FALSE, name="Producciones")

g_2 <- plot_ly(d_2, x=~Año)
g_2 <- g_2 |> add_trace(y=~Producciones, 
                            type = 'scatter', mode = 'lines',
                            line = list(color='rgba(104,255,0, 1)', width = 6))

g_2
```


### ALEXANDER RODRIGUEZ BUSTAMANTE
```{r}
d_4 <- produccion_grupos[[3]] |> 
  separate_rows(autores, sep = ", ") |> 
  filter(autores == "ALEXANDER RODRIGUEZ BUSTAMANTE", 
         ano <=2020, ano >=2016)|>
  select(ano) |> 
  mutate(Año = str_trim(ano)) |> 
  select(-ano) |> 
  count(Año, sort=FALSE, name="Producciones")

g_4 <- plot_ly(d_4, x=~Año)
g_4 <- g_4 |> add_trace(y=~Producciones, 
                            type = 'scatter', mode = 'lines',
                            line = list(color='rgba(104,255,0, 1)', width = 6))

g_4
```


# Investigadores - Detalle