schoolar <-
  tibble(integrante =c("Yamile Cardona Maya",
                       "Víctor Daniel  Gil Vera",
                       "andres mauricio grisales aguirre",
                       "Edgar Andrés Chavarriaga Miranda",
                       "Franklin Ferraro Gómez",
                       "GABRIEL JAIME  POSADA HERNANDEZ",
                       "Ingrid Durley Torres  Pardo",
                       "Lina Maria Montoya  Suárez",
                       "Luis Fernando Cardona Palacio",
                       "Maria Julia Nieto Callejas",
                       "MARIO ALEJANDRO LÓPEZ OCAMPO",
                       "Mauricio López Bonilla",
                       "Sara María Aguilar Sierra",
                       "Shirlene Patricia  Vega ROYERO",
                       "SUYIS YAJAIRA LOZANO GARCÍA",
                       "Walter Hugo Arboleda Mazo",
                       "Elvigia Cardona  ZULETA",
                       "Jorge Eduardo Vasquez Santamaria",
                       "Dany Steven Gómez Agudelo",
                       "David Andrés Díez Gómez",
                       "JORGE IVAN GAVIRIA MESA",
                       "Juan Esteban  Aguirre  Espinosa",
                       "Laura Victoria  Cardenas Rojas",
                       "Maria Isabel  Uribe López",
                       "Mauricio Mejia Lobo",
                       "Mayda Soraya Marín  Galeano",
                       "Roberto Mauricio Romero Cárdenas",
                       "Jenniffer Londoño Jurado",
                       "Jormaris Martínez Gómez",
                       "Luis Fernando Quintero Arango",
                       "ana maría  chaux gutiérrez",
                       "Daniel Muñoz Quintero",
                       "Jaime Alberto Beltrán Ríos",
                       "JORGE IVAN JIMENEZ  SANCHEZ",
                       "José Antonio López Giraldo",
                       "Mauricio alejandro bedoya jimenez",
                       "Néstor Eduardo Flórez  OVIEDO",
                       "Sandra Milena Malavera Pineda",
                       "Sebastián Arias Giraldo",
                       "Sindy Yuliana Gallego Tavera",
                       "Sugey Elena Anaya García",
                       "Ubeimar Aurelio Osorio Atehortúa",
                       "Víctor Daniel  Gil Vera",
                       "Victor Hugo Meriño Córdoba",
                       "YAMARU DEL VALLE CHIRINOS ARAQUE",
                       "Fredy De Jesus Fernández Márquez",
                       "Juan Santiago Calle Piedrahita",
                       "Olga Lucía Arboleda Álvarez",
                       "Martha del Socorro  Alzate Cárdenas",
                       "Doralice Ortiz Ortiz",
                       "Jaime Antero Arango Marin",
                       "Laura Elena Zapata Jiménez",
                       "Maria Isabel GUERRERO MOLINA",
                       "Oswaldo Antonio Salgado Cañaveral",
                       "Pedro Luis Duque Hurtado",
                       "SEBASTIAN ROBLEDO GIRALDO",
                       "Victoria Blaquised Rivera",
                       "YAMARU DEL VALLE CHIRINOS ARAQUE",
                       "Olber Eduardo Arango Tobón",
                       "Julio Antonio  Olivera La Rosa",
                       "ANYERSON STITHS GOMEZ  TABARES",
                       "Catalina Quintero López",
                       "César Andrés  Carmona Cardona",
                       "Claudia Marcela Arana Medina",
                       "Daniel alfredo landinez martinez",
                       "Isabel Cristina Puerta Lopera",
                       "Juan Diego Betancur Arias",
                       "Omar Augusto Amador Sánchez",
                       "Paula Andrea Montoya Zuluaga",
                       "Víctor Daniel  Gil Vera",
                       "Carmen Ysabel Martínez de Meriño",
                       )
         
         id = c ("Y2p7DZwAAAAJ&hl",
                 "1-4BHH8AAAAJ&hl",
                 "-urmP7EAAAAJ&hl",
                 "qSOzbFwAAAAJ",
                 "DNeZOJUAAAAJ&hl",
                 "_uwscnEAAAAJ&hl",
                 "nchHazIAAAAJ&hl",
                 "7Y-8siIAAAAJ&hl",
                 "hOgH7HAAAAAJ&hl",
                 "XuxhAV0AAAAJ&hl",
                 "fDz4KKEAAAAJ&hl",
                 "lQqAfmwAAAAJ&hl",
                 "_RFI4pkAAAAJ&hl",
                 "yQ7g9xUAAAAJ&hl",
                 "z1vjdF0AAAAJ",
                 "uFJHflEAAAAJ&hl",
                 "SteXGqYAAAAJ&hl",
                 "v8GT-VAAAAAJ&hl",
                 "YaysRIIAAAAJ&hl",
                 "sOWnFLUAAAAJ&hl",
                 "mh-AeYwAAAAJ",
                 "9QD3rjkAAAAJ",
                 "VlC916UAAAAJ",
                 "QbjM9m0AAAAJ",
                 "RCtbsjMAAAAJ",
                 "1x5m4ywAAAAJ",
                 "YdeOxzsAAAAJ",
                 "XFBxR6kAAAAJ",
                 "3vFUn4wAAAAJ",
                 "vu06sqwAAAAJ",
                 "ZBh57LoAAAAJ&hl",
                 "Fp-EtWwAAAAJ",
                 "bjYfxdwAAAAJ",
                 "FF97f1MAAAAJ",
                 "jCYg-jsAAAAJ",
                 "wDY8t8gAAAAJ",
                 "3oUj4vUAAAAJ",
                 "qvBehKYAAAAJ",
                 "V3rISaoAAAAJ",
                 "YNwDcOcAAAAJ",
                 "qPSF-CgAAAAJ",
                 "MTw3GSYAAAAJ&hl",
                 "1-4BHH8AAAAJ",
                 "dsuvvNEAAAAJ",
                 "NzpSyf0AAAAJ",
                 "1aXOG-MAAAAJ",
                 "sXijM8EAAAAJ",
                 "94o7mbgAAAAJ",
                 "bEZsTPUAAAAJ",
                 "syisuJcAAAAJ",
                 "qn1Kr9EAAAAJ",
                 "IjPj8zoAAAAJ",
                 "PXnaNH4AAAAJ",
                 "R1p685wAAAAJ",
                 "tEPrd4IAAAAJ&hl",
                 "RGUTAfEAAAAJ&hl",
                 "oZ4fX-IAAAAJ&hl",
                 "NzpSyf0AAAAJ",
                 "nIWo18gAAAAJ",
                 "p1jzZwMAAAAJ&hl",
                 "504O9wUAAAAJ",
                 "jp1wLg4AAAAJ",
                 "LN9Fg-8AAAAJ",
                 "bEplYn8AAAAJ",
                 "HWzOMPwAAAAJ",
                 "I7x7Oo8AAAAJ",
                 "Rb881xwAAAAJ",
                 "2EdSYP0AAAAJ&hl",
                 "_SE2G3UAAAAJ",
                 "1-4BHH8AAAAJ",
                 "a5eJhxMAAAAJ",
           
         ))