scholar <- 
  tibble(integrante =c("Angela María  Velásquez  Velásquez",
                       "Alfredo Manuel Ghiso Cotos",
                       "Jenny Marcela Acevedo Valencia",
                       "Natalia Andrea Alzate Alzate",
                       "Ruby Stella Cabrera Jaramillo",
                       "Mauricio alejandro bedoya jimenez",
                       "MARLON DAVID GARCIA JIMENEZ",
                       "Farley Sary Rojas  Restrepo",
                       "Carlos Eduardo Castaño Rios",
                       "Candy Lorena Chamorro  Gonzalez",
                       "Carolina Vila Porras",
                       "Andrés Felipe Agudelo Zorrilla",
                       "andres escobar vasquez",
                       "Paloma  Marín Escobar",
                       "Manuel David Gómez Erazo",
                       "Kelly Vargas García",
                       "Juan Sebastián Hernández Valencia",
                       "Juan Esteban Londoño Betancur",
                       "Andrés Alfredo Castrillón Castrillón",
                       "Marcos VEGA SEÑA",
                       "Juan Diego López Medina",
                       "Jhoeen Sneyder Rojas Díaz",
                       "Edwin Andrés Sepúlveda Cardona",
                       "Carlos Suárez Quiceno",
                       "CARLOS ANDRÉS TREJOS GIL",
                       "Lina María Rendón López",
                       "Alexander Rodríguez Bustamante",
                       "YUSTY CAROLINA RESTREPO SEGURA",
                       "Olena Klimenko Klimenko",
                       "Mauricio alejandro bedoya jimenez",
                       "Maricelly Gómez Vargas",
                       "Maria Victoria Restrepo Tobón",
                       "Lucas Davila Cañas",
                       "Lina María Gallego Ramírez",
                       "Jorge Hernán González Cortés",
                       "Gloria Maria Lopez Arboleda",
                       "Gloria Cecilia Cardona Rios",
                       "Gladys Janeth Ríos Palacio",
                       "Eliza Kratc  Gil",
                       "David Ignacio Molina Velásquez",
                       "SANDRA MILENA RESTREPO ESCOBAR",
                       "Dubis Marcela Rincon Barreto",
                       "Viviana Carmenza  Avila Navarrete",
                       "Benilda Layne Bernal",
                       "Estelio Jose Angulo",
                       "Carlos RODRIGUEZ SANTOS",
                       "Argemiro Jose AMAYA BUELVAS",
                       "Victor Teran Reales",
                       "HUBER YECID CASTRO ESCOBAR",
                       "Sandra Isabel Mejia Zapata",
                       "Paula Vanessa Sanchez Agudelo",
                       "María Cristina Correa Duque",
                       "Magda Victoria Díaz Alzate",
                       "Katy Luz Millán Otero",
                       "Jose Alcides Castro Acevedo",
                       "John Harvy Arcia Grajales",
                       "Herwin Eduardo Cardona Quitián",
                       "Heidi Smith Pulido Varon",
                       "Carolina  Valdés Henao",
                       "ANYERSON STITHS GOMEZ  TABARES",
                       "Nicolasa María Durán Palacio",
                       "Yubisay Noiraly Mejías Peña",
                       "OVIDIO HERRERA RIVERA",
                       "Mónica María Castañeda Gómez",
                       "Lucas Davila Cañas",
                       "Ledy Maryory  Bedoya  Cardona",
                       "Carolina  Vásquez  López",
                       "Alexander Rodríguez Bustamante",
                       "Edison Francisco Viveros Chavarría",
                       "LEISY MAGDALI  ARROYAVE TABORDA",
                       "YUSTY CAROLINA RESTREPO SEGURA",
                       "Sonia Ruth Quintero  Arrubla",
                       "Oscar Peláez Henao",
                       "Jose Wilmar Pino Montoya",
                       "José Vicente Abad Olaya",
                       "José Federico Agudelo Torres",
                       "Claudia Marcela Arana Medina",
                       "Bairon Jaramillo Valencia",
                       "Adriana Maria Gallego Henao",
                       "Mónica María Alvarez Gallego",
                       ),
         id = c("BbHGEOcAAAAJ&hl",
                "Cj2hqc4AAAAJ&hl",
                "ul0fN9wAAAAJ",
                "sAljacYAAAAJ",
                "_Swwv5oAAAAJ",
                "wDY8t8gAAAAJ",
                "zwGXNrAAAAAJ",
                "Q0JvK8cAAAAJ&hl",
                "LRUmr_cAAAAJ",
                "vOpE5gUAAAAJ&hl",
                "Kd1AWwkAAAAJ",
                "GJRrDiEAAAAJ&hl",
                "HgkxSmsAAAAJ",
                "sRuFPZsAAAAJ",
                "ZN11BuUAAAAJ",
                "FSZpothCoVgC",
                "YulZHwUAAAAJ",
                "kmGAVz0AAAAJ&hl",
                "09VhuCYAAAAJ",
                "h3lf-PsAAAAJ",
                "5rZW9KcAAAAJ",
                "SuGmv1UAAAAJ",
                "KH7yFUsAAAAJ",
                "1ATgz8UAAAAJ",
                "Hw7ZjsEAAAAJ",
                "6uKvLyYAAAAJ",
                "F2CwSh0AAAAJ",
                "BhyHthYAAAAJ",
                "0r6pOxoAAAAJ",
                "wDY8t8gAAAAJ",
                "XNkEWKgAAAAJ",
                "R5D6vOoAAAAJ",
                "mCT8CTsAAAAJ",
                "WPEpjKwAAAAJ",
                "BfjlQ8QAAAAJ",
                "iR3xAfEAAAAJ",
                "zt9fGF0AAAAJ",
                "I8eYYScAAAAJ",
                "r1I0YJYAAAAJ",
                "xCRCMooAAAAJ",
                "eHauI0IAAAAJ",
                "pjSE_C0AAAAJ",
                "c1XCBZ0AAAAJ",
                "Cw9U7VIAAAAJ",
                "NRo7HZIAAAAJ",
                "FmH8nIkAAAAJ&hl",
                "kyNzB50AAAAJ",
                "lOUtSkIAAAAJ&hl",
                "jsQSXroAAAAJ",
                "IiNO1TwAAAAJ",
                "SosfQ4QAAAAJ",
                "GsRFkT8AAAAJ",
                "C9ZdWuEAAAAJ",
                "-RwHy5gAAAAJ",
                "iXbqjRQAAAAJ",
                "dyMWHucAAAAJ",
                "Ojpa1lAAAAAJ",
                "5ZIDAcEAAAAJ",
                "r-CYB90AAAAJ",
                "504O9wUAAAAJ",
                "ULpZsLAAAAAJ",
                "82UcqOgAAAAJ",
                "gcjNnGEAAAAJ",
                "-4_OX-cAAAAJ&hl",
                "R5D6vOoAAAAJ",
                "6vKCOHYAAAAJ",
                "2rKBGpEAAAAJ",
                "KcmOLKYAAAAJ",
                "F2CwSh0AAAAJ",
                "00wsl70AAAAJ",
                "KVBCFWkAAAAJ",
                "BhyHthYAAAAJ",
                "Bo9j0C0AAAAJ",
                "WasxVdYAAAAJ&hl",
                "LhNZ3BgAAAAJ",
                "trVcxggAAAAJ",
                "RHbX7ioAAAAJ",
                "bEplYn8AAAAJ",
                "2b28iRkAAAAJ",
                "zts5sHIAAAAJ",
                "sw3ZQ-kAAAAJ"
                ))
